"""
HTML Reporter Module

Outputs scan results as an HTML report.
"""

import sys
from typing import Optional
from datetime import datetime

from core.scanner import ScanResults
from mappers.masvs_mapper import MasvsMapper


class HtmlReporter:
    """
    Reporter that outputs findings as an HTML report.
    
    Generates a standalone HTML file with interactive features
    and professional styling.
    """
    
    def __init__(self, output_path: Optional[str] = None):
        """
        Initialize the HTML reporter.
        
        Args:
            output_path: If provided, output will be written to this file
        """
        self.output_path = output_path or 'security_report.html'
        self.masvs_mapper = MasvsMapper()
    
    def generate(self, results: ScanResults):
        """
        Generate HTML report.
        
        Args:
            results: ScanResults object containing findings
        """
        html = self._build_html(results)
        self._write_to_file(html)
        print(f"HTML report generated: {self.output_path}")
    
    def _build_html(self, results: ScanResults) -> str:
        """Build the HTML report."""
        findings_html = self._build_findings_html(results)
        compliance_html = self._build_compliance_html(results)
        
        return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flutter Security Scan Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        header {{ background: linear-gradient(135deg, #1a237e 0%, #0d47a1 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 20px; }}
        header h1 {{ font-size: 2rem; margin-bottom: 10px; }}
        header p {{ opacity: 0.9; }}
        .card {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .card h2 {{ color: #1a237e; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 2px solid #e3f2fd; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .stat {{ text-align: center; padding: 15px; border-radius: 8px; }}
        .stat-critical {{ background: #ffebee; color: #c62828; }}
        .stat-high {{ background: #fff3e0; color: #ef6c00; }}
        .stat-medium {{ background: #e3f2fd; color: #1565c0; }}
        .stat-low {{ background: #e0f7fa; color: #00838f; }}
        .stat-info {{ background: #f5f5f5; color: #616161; }}
        .stat h3 {{ font-size: 2rem; margin-bottom: 5px; }}
        .finding {{ border-left: 4px solid #ccc; padding: 15px; margin-bottom: 15px; background: #fafafa; border-radius: 0 8px 8px 0; }}
        .finding-critical {{ border-color: #c62828; }}
        .finding-high {{ border-color: #ef6c00; }}
        .finding-medium {{ border-color: #1565c0; }}
        .finding-low {{ border-color: #00838f; }}
        .finding-info {{ border-color: #616161; }}
        .finding h3 {{ margin-bottom: 10px; }}
        .finding-meta {{ font-size: 0.9rem; color: #666; margin-bottom: 10px; }}
        .finding-meta span {{ margin-right: 15px; }}
        .code-snippet {{ background: #263238; color: #aed581; padding: 15px; border-radius: 4px; overflow-x: auto; font-family: 'Monaco', 'Menlo', monospace; font-size: 0.85rem; margin: 10px 0; }}
        .remediation {{ background: #e8f5e9; padding: 10px; border-radius: 4px; margin-top: 10px; }}
        .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: bold; text-transform: uppercase; }}
        .badge-critical {{ background: #c62828; color: white; }}
        .badge-high {{ background: #ef6c00; color: white; }}
        .badge-medium {{ background: #1565c0; color: white; }}
        .badge-low {{ background: #00838f; color: white; }}
        .badge-info {{ background: #616161; color: white; }}
        .compliance-table {{ width: 100%; border-collapse: collapse; }}
        .compliance-table th, .compliance-table td {{ padding: 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }}
        .compliance-table th {{ background: #f5f5f5; font-weight: 600; }}
        .status-pass {{ color: #2e7d32; }}
        .status-fail {{ color: #c62828; }}
        footer {{ text-align: center; padding: 20px; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🔒 Flutter Security Scan Report</h1>
            <p>Generated by Flutter Security Scanner v{results.scanner_version}</p>
            <p>MSc Cybersecurity Project - University of Chester</p>
        </header>

        <div class="card">
            <h2>📊 Scan Overview</h2>
            <p><strong>Path:</strong> {results.scan_path}</p>
            <p><strong>Timestamp:</strong> {results.scan_timestamp}</p>
            <p><strong>Duration:</strong> {results.scan_duration_seconds:.2f} seconds</p>
            <p><strong>Files Scanned:</strong> {results.total_files_scanned}</p>
            <p><strong>Lines Scanned:</strong> {results.total_lines_scanned}</p>
        </div>

        <div class="card">
            <h2>📈 Summary</h2>
            <div class="stats">
                <div class="stat stat-critical">
                    <h3>{results.critical_count}</h3>
                    <p>Critical</p>
                </div>
                <div class="stat stat-high">
                    <h3>{results.high_count}</h3>
                    <p>High</p>
                </div>
                <div class="stat stat-medium">
                    <h3>{results.medium_count}</h3>
                    <p>Medium</p>
                </div>
                <div class="stat stat-low">
                    <h3>{results.low_count}</h3>
                    <p>Low</p>
                </div>
                <div class="stat stat-info">
                    <h3>{results.info_count}</h3>
                    <p>Info</p>
                </div>
            </div>
        </div>

        <div class="card">
            <h2>✅ MASVS Compliance</h2>
            {compliance_html}
        </div>

        <div class="card">
            <h2>🔍 Detailed Findings ({results.total_findings})</h2>
            {findings_html}
        </div>

        <footer>
            <p>Flutter Security Scanner - MSc Cybersecurity Project</p>
            <p>Caleb Elebhose - University of Chester - {datetime.now().year}</p>
        </footer>
    </div>
</body>
</html>'''
    
    def _build_findings_html(self, results: ScanResults) -> str:
        """Build HTML for findings section."""
        if not results.findings:
            return '<p style="color: #2e7d32; font-weight: bold;">✅ No vulnerabilities found!</p>'
        
        html_parts = []
        for finding in results.findings:
            code_snippet = finding.code_snippet.replace('<', '&lt;').replace('>', '&gt;')
            
            html_parts.append(f'''
            <div class="finding finding-{finding.severity}">
                <h3>
                    <span class="badge badge-{finding.severity}">{finding.severity}</span>
                    {finding.title}
                </h3>
                <div class="finding-meta">
                    <span>📁 {finding.file_path}</span>
                    <span>📍 Line {finding.line_number}</span>
                    <span>🏷️ {finding.vulnerability_id}</span>
                    <span>📋 {finding.masvs_control}</span>
                    {f'<span>🔗 {finding.cwe_id}</span>' if finding.cwe_id else ''}
                </div>
                <p>{finding.description}</p>
                <div class="code-snippet"><pre>{code_snippet}</pre></div>
                <div class="remediation">
                    <strong>💡 Remediation:</strong> {finding.remediation}
                </div>
            </div>
            ''')
        
        return '\n'.join(html_parts)
    
    def _build_compliance_html(self, results: ScanResults) -> str:
        """Build HTML for compliance table."""
        compliance = self.masvs_mapper.get_compliance_summary(results.findings)
        
        rows = []
        for category_id, category_data in compliance.items():
            status_class = 'status-pass' if category_data['status'] == 'PASS' else 'status-fail'
            status_icon = '✅' if category_data['status'] == 'PASS' else '❌'
            
            rows.append(f'''
            <tr>
                <td><strong>{category_id}</strong></td>
                <td>{category_data['name']}</td>
                <td>{category_data['findings_count']}</td>
                <td class="{status_class}">{status_icon} {category_data['status']}</td>
            </tr>
            ''')
        
        return f'''
        <table class="compliance-table">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Name</th>
                    <th>Findings</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
        '''
    
    def _write_to_file(self, html: str):
        """Write HTML output to file."""
        try:
            with open(self.output_path, 'w', encoding='utf-8') as f:
                f.write(html)
        except IOError as e:
            print(f"Error writing to file: {e}", file=sys.stderr)
